name: Comment on Issue Using gh CLI

on:
  issues:
    types: [opened, labeled]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate GitHub CLI with GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GITHUB_TOKEN" | gh auth login --with-token

      - name: Get issue labels using gh CLI
        id: get-labels
        run: |
          labels=$(gh issue view ${{ github.event.issue.number }} --json labels --jq '.labels[].name')
          echo "labels=$labels" >> $GITHUB_ENV
          echo "Issue Labels: $labels"

      - name: Comment on issue using gh CLI
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "The following labels were found on this issue: ${{ env.labels }}"
