name: Create a PR for release issues
on:
  issues:
    types: [opened, labeled, edited]

jobs:
  create-pr:
    if: contains(github.event.issue.labels.*.name, 'Release')  # This ensures the job only runs if the 'Release' label is present
    runs-on: ubuntu-latest    
    permissions:
      issues: write
      pull-requests: write
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Create PR and comment
        id: branch-creation
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}        
        run: |
          version=$(echo "${{ github.event.issue.title }}" | sed -n 's/.*rc\/\(v[0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')

          # Early return if issue name is not correct
          if [ -z "$version" ]; then
            gh issue comment ${{ github.event.issue.number }} --body "Version number is not present or incorrect."                        
            exit 1
          fi          

          branch_name="rc/$version"
          body_branch_present="A new branch named \`$branch_name\` was already present in the repository and a [pull request]($pr_url) has been opened to merge this branch into \`main\`."
          body_branch_not_present="A new branch named \`$branch_name\` has been created and a [pull request]($pr_url) has been opened to merge this branch into \`main\`."
          
          # Check if the branch exists on the remote
          if git ls-remote --heads origin "$branch_name" | grep "$branch_name"; then
            echo "Branch already exists: $branch_name"
            body=$body_branch_present
          else
            git checkout -b "$branch_name"
            git push origin "$branch_name"            
            echo "Creating branch: $branch_name"            
            body=$body_branch_not_present
          fi

          echo "Creating PR"
          pr_url=$(gh pr create --base main --head "$branch_name" -l "Release" -F .github/PULL_REQUEST_TEMPLATE/pull_request_template.md -t "${{ github.event.issue.title }}")

          echo "Creating comment"
          gh issue comment ${{ github.event.issue.number }} --body $body 

          

            